# Hardware config for Battery Management System Go4-23e
module_name: "CIB"
use_hw_timer: false # Disable hw timer based DMA update

buckets:
    # Current Sensor ADCs
    high_frequency_cib:
        frequency_hz: 250
        parameters:
            bmsTractiveSystemCurrentLow_A:
                ADC: ADC1_IN1
                sensor: current_sensor_1
                samples_buffered: 1
            bmsTractiveSystemCurrentHigh_A:
                ADC: ADC1_IN0
                sensor: current_sensor_2
                samples_buffered: 1
    
    medium_frequency_cib:
        frequency_hz: 25
        parameters:
            soeByOCV_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            soeByCoulombCounting_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # Info LF
            bmsAveBrickVoltage_V:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMaxBrickVoltage_V:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMinBrickVoltage_V:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsAveBrickTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMaxBrickTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMinBrickTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsAveBoardTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMaxBoardTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsMinBoardTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

    low_frequency_cib:
        frequency_hz: 4
        parameters:
            # Charger Interface Board
            sdcStatus1:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            sdcStatus2:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            sdcStatus3:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            sdcStatus4:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # Error states
            amsFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            imdFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bspdFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            imdFaultInfo_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsNumActiveAlerts_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsCurrAlertIndex_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsAlertMessage_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsCurrAlertIsLatched_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            # AMS Faults
            bmsOvervoltageFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsUndervoltageFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsOvertempFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsBmbCommunicationFailureAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsBadVoltageSenseStatusAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsInsufficientTempSensorsAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerOverVoltageAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerOverCurrentAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerVoltageMismatchAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerCurrentMismatchAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerHardwareFailureAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerOverTempAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1


            # Other Alerts
            bmsOvervoltageWarningAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsUndervoltageWarningAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsCellImbalanceAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsOvertempWarningAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsAmsSdcFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsBspdSdcFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsImdSdcFaultAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsCurrentSensorErrorAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsBadBrickTempSenseStatusAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsBadBoardTempSenseStatusAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            bmsStackVsSegmentImbalanceAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerInputVoltageErrorAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerBatteryNotDetectedErrorAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            bmsChargerCommunicationErrorAlert_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
                